### ISSUE TITLE
Is it possible to make a suckEffect out of this? 

### ISSUE THREAD

**Issue by catlan** [Ciechan/BCGenieEffect#7]
suckEffect: http://stackoverflow.com/questions/428110/how-can-i-replicate-the-trashing-animation-of-mail-app

Thx,
Christopher

**Comment by Ciechan** [comment]
If you want to replicate suck effect exactly, then the answer is no, since genie effect keeps the top and bottom edge parallel (when animating up and down) and Apple's suck effect makes a dent at the center of top edge. However, if you can live without this feature than you can change the shape of enclosing Bezier curves by modifying `c1` and `c2` control points inside `bezierAxisIntersection` function to make it look as you want. Exact calculations are left as an exercise to the reader.

**Comment by catlan** [comment]
Thx, when I have time I will look into it!
